# Basic `dependabot.yml` file with
# minimum configuration

version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      # Check for updates on Saturday
      day: "saturday"
      # Check when starting the updates
      time: "04:00"
    target-branch: "main"
    # Enable a limit for pull requests for Docker dependencies
    open-pull-requests-limit: 10

  # Enable version updates for Docker on dev branch
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
    target-branch: "dev"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    # Actions are pinned to full SHAs for supply-chain security.
    # Dependabot does not reliably update SHA-pinned actions; ignore all action updates.
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

  # Maintain dependencies for GitHub Actions on dev branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 10
    # Ignore all action updates for SHA-pinned workflows
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
