name: Dependabot Reviewer

on:
  pull_request_target:
    branches: [dev]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-review:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/dependabot-reviewer.yml@442c07e0fbad1bce2ad7ad1a335d240c7cd7892e
    with:
      auto_merge: true
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}  # 👈 pass your PAT here
