name: Dependabot Reviewer

on:
  pull_request_target:
    branches: [dev]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-review:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/dependabot-reviewer.yml@59060bc1638e529124ada1bf795f55dff0de9bad
    with:
      auto_merge: true
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}  # 👈 pass your PAT here
