name: Dependabot Reviewer

on:
  pull_request_target:
    branches: [dev]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-review:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/dependabot-reviewer.yml@4ffe7f1040213a9743f4fc8fbf8aaa918ff1565f
    with:
      auto_merge: true
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}  # 👈 pass your PAT here
