name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@35d8f9f154dbccb6898e6e308baaad73a497d95c
    with:
      source_branch: main
      target_branch: dev
