name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@442c07e0fbad1bce2ad7ad1a335d240c7cd7892e
    with:
      source_branch: main
      target_branch: dev
