name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@7f65c3b60d9a345cd060eb2f12360c9c28aa6879
    with:
      source_branch: main
      target_branch: dev
